export const RECENT_NEWS = [
  {
    id: 1,
    title: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
    imageUrl: "/images/news1.png",
    elapsedTime: "2 minutes ago",
    body: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Numquam ut ipsa sit, nulla laboriosam nesciunt ea, officiis, aliquam molestiae quibusdam sequi atque! Natus architecto qui, dolor provident quas eos nostrum?",
    date: "2022-08-22",
  },
  {
    id: 2,
    title: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
    imageUrl: "/images/news2.png",
    elapsedTime: "2 minutes ago",
    body: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Numquam ut ipsa sit, nulla laboriosam nesciunt ea, officiis, aliquam molestiae quibusdam sequi atque! Natus architecto qui, dolor provident quas eos nostrum?",
    date: "2022-08-22",
  },
  {
    id: 3,
    title: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
    imageUrl: "/images/news3.png",
    elapsedTime: "2 minutes ago",
    body: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Numquam ut ipsa sit, nulla laboriosam nesciunt ea, officiis, aliquam molestiae quibusdam sequi atque! Natus architecto qui, dolor provident quas eos nostrum?",
    date: "2022-08-22",
  },
  {
    id: 4,
    title: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
    imageUrl: "/images/news4.png",
    elapsedTime: "2 minutes ago",
    body: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Numquam ut ipsa sit, nulla laboriosam nesciunt ea, officiis, aliquam molestiae quibusdam sequi atque! Natus architecto qui, dolor provident quas eos nostrum?",
    date: "2022-08-22",
  },
  {
    id: 5,
    title: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
    imageUrl: "/images/news5.png",
    elapsedTime: "2 minutes ago",
    body: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Numquam ut ipsa sit, nulla laboriosam nesciunt ea, officiis, aliquam molestiae quibusdam sequi atque! Natus architecto qui, dolor provident quas eos nostrum?",
    date: "2022-08-22",
  },
  {
    id: 6,
    title: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
    imageUrl: "/images/news6.png",
    elapsedTime: "2 minutes ago",
    body: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Numquam ut ipsa sit, nulla laboriosam nesciunt ea, officiis, aliquam molestiae quibusdam sequi atque! Natus architecto qui, dolor provident quas eos nostrum?",
    date: "2022-08-22",
  },
  {
    id: 7,
    title: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
    imageUrl: "/images/news7.png",
    elapsedTime: "2 minutes ago",
    body: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Numquam ut ipsa sit, nulla laboriosam nesciunt ea, officiis, aliquam molestiae quibusdam sequi atque! Natus architecto qui, dolor provident quas eos nostrum?",
    date: "2022-08-22",
  },
];
